name: Minecraft_Project
author: Cynigasm
authors: [Trigary]
main: com.cynigasm.projects.minecraft.Project
version: 0.1

commands:
  social:
    description: Friends manager commands
    usage: /friends
  clan:
    description: Clan manager commands
    usage: §cUsage:§f /clan | /clan create <name>