name: Minecraft_Project
author: Cynigasm
authors: [Trigary]
main: com.cynigasm.projects.minecraft.Project
version: 0.1

commands:
  social:
    description: Friends manager commands
    usage: /friends
  clan:
    description: Clan manager commands
    usage: §cUsage:§f /clan | /clan create <name>
  schematics:
    description: Schematics manager commands
    usage: |
      §cUsage:§f /schematics save <name> <X1> <Y1> <Z1> <X2> <Y2> <Z2>
      §cUsage:§f /schematics load <name>
      §cUsage:§f /schematics load <empire> <name>